# Generated by Django 4.1.4 on 2023-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='demand',
            field=models.TextField(default='Описание', verbose_name='Востребованность'),
        ),
    ]
